-- Preserve the full subject-preparation question structure generated by ingestion.
ALTER TABLE public.questions
    ADD COLUMN IF NOT EXISTS source_question_id TEXT,
    ADD COLUMN IF NOT EXISTS question_type TEXT
        CHECK (question_type IN ('MCQ', 'Theory')),
    ADD COLUMN IF NOT EXISTS options JSONB NOT NULL DEFAULT '[]'::jsonb,
    ADD COLUMN IF NOT EXISTS explanation TEXT,
    ADD COLUMN IF NOT EXISTS subtopic TEXT;

CREATE UNIQUE INDEX IF NOT EXISTS questions_topic_source_question_id_key
    ON public.questions (topic_id, source_question_id)
    WHERE source_question_id IS NOT NULL;